<?xml version="1.0" standalone="yes"?>

<?program_dtd version="1"?>

<!DOCTYPE PROGRAM [

<!ELEMENT PROGRAM (DESCRIPTION?,
                   INFO_SOURCE?,
                   PROCESSOR?,
                   COMPILER?,
                   DATATYPES?,
                   MEMORY_MAP?,
                   REGISTER_VALUES?,
                   CODE?,
                   DATA?,
                   EQUATES?,
                   COMMENTS?,
                   PROPERTIES?,
                   BOOKMARKS?,
                   PROGRAM_TREES?,
                   PROGRAM_ENTRY_POINTS?,
                   RELOCATION_TABLE?,
                   SYMBOL_TABLE?,
                   FUNCTIONS?,
                   MARKUP?,
                   EXT_LIBRARY_TABLE?)>
  <!ATTLIST PROGRAM NAME       CDATA #REQUIRED>
  <!ATTLIST PROGRAM EXE_PATH   CDATA #IMPLIED>
  <!ATTLIST PROGRAM EXE_FORMAT CDATA #IMPLIED>
  <!ATTLIST PROGRAM IMAGE_BASE CDATA #IMPLIED>

<!ELEMENT DISPLAY_SETTINGS EMPTY>
  <!ATTLIST DISPLAY_SETTINGS FORMAT           (hex | decimal | octal | binary | char) #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SIGNED           (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ZERO_PAD         (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ENDIAN           (big | little)                          #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SHOW_TERMINATOR  (y | n)                                 #IMPLIED>

<!ELEMENT DESCRIPTION    (#PCDATA)>
<!ELEMENT REGULAR_CMT    (#PCDATA)>
<!ELEMENT REPEATABLE_CMT (#PCDATA)>
<!ELEMENT TYPEINFO_CMT   (#PCDATA)>

<!ELEMENT INFO_SOURCE EMPTY>
  <!ATTLIST INFO_SOURCE USER      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TOOL      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE FILE      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TIMESTAMP CDATA #IMPLIED>

<!ELEMENT PROCESSOR EMPTY>
  <!ATTLIST PROCESSOR NAME              CDATA          #REQUIRED>
  <!ATTLIST PROCESSOR FAMILY            CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR LANGUAGE_PROVIDER CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR ENDIAN            (big | little) #IMPLIED>
  <!ATTLIST PROCESSOR ADDRESS_MODEL     CDATA          #IMPLIED>

<!-- TODO: expand compiler tag -->
<!ELEMENT COMPILER EMPTY>
  <!ATTLIST COMPILER NAME CDATA #REQUIRED>

<!ELEMENT MEMORY_MAP (MEMORY_SECTION*)>

<!ELEMENT MEMORY_SECTION ((MEMORY_CONTENTS*) | (BIT_MAPPED?))>
  <!ATTLIST MEMORY_SECTION NAME         CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION START_ADDR   CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION LENGTH       CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION PERMISSIONS  (r | w | x | rw | rx | wx | rwx)  #IMPLIED>
  <!ATTLIST MEMORY_SECTION VOLATILE     (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION ARTIFICIAL   (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION COMMENT      CDATA                             #IMPLIED>

<!ELEMENT MEMORY_CONTENTS EMPTY>
  <!ATTLIST MEMORY_CONTENTS START_ADDR   CDATA  #IMPLIED>
  <!ATTLIST MEMORY_CONTENTS FILE_NAME    CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS FILE_OFFSET  CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS LENGTH       CDATA  #IMPLIED>

<!ELEMENT BIT_MAPPED EMPTY>
  <!ATTLIST BIT_MAPPED SOURCE_ADDRESS  CDATA  #REQUIRED>

<!ELEMENT REGISTER_VALUES (REGISTER_VALUE_RANGE*)>

<!ELEMENT REGISTER_VALUE_RANGE EMPTY>
  <!ATTLIST REGISTER_VALUE_RANGE REGISTER      CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE VALUE         CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE START_ADDRESS CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE LENGTH        CDATA #REQUIRED>

<!ELEMENT CODE (CODE_BLOCK*)>

<!ELEMENT CODE_BLOCK EMPTY>
  <!ATTLIST CODE_BLOCK  START  CDATA  #REQUIRED>
  <!ATTLIST CODE_BLOCK  END    CDATA  #REQUIRED>

<!ELEMENT DATA (DEFINED_DATA*)>

<!ELEMENT DEFINED_DATA (TYPEINFO_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST DEFINED_DATA ADDRESS             CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST DEFINED_DATA SIZE                CDATA  #IMPLIED>

<!ELEMENT EQUATES (EQUATE_GROUP*)>

<!ELEMENT EQUATE_GROUP (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, (EQUATE | BIT_MASK)*)>
  <!ATTLIST EQUATE_GROUP NAME       CDATA       #IMPLIED>
  <!ATTLIST EQUATE_GROUP BIT_FIELD  (yes | no)  #IMPLIED>

<!ELEMENT EQUATE (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST EQUATE NAME     CDATA  #REQUIRED>
  <!ATTLIST EQUATE VALUE    CDATA  #REQUIRED>
  <!ATTLIST EQUATE BIT_MASK CDATA  #IMPLIED>

<!ELEMENT BIT_MASK (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST BIT_MASK NAME   CDATA  #REQUIRED>
  <!ATTLIST BIT_MASK VALUE  CDATA  #REQUIRED>

<!ELEMENT COMMENTS (COMMENT*)>

<!ELEMENT COMMENT (#PCDATA)>
  <!ATTLIST COMMENT ADDRESS  CDATA                                            #REQUIRED>
  <!ATTLIST COMMENT TYPE     (end-of-line | repeatable | pre | post | plate)  #REQUIRED>

<!ELEMENT PROPERTIES (PROPERTY*)>

<!ELEMENT PROPERTY EMPTY>
  <!ATTLIST PROPERTY NAME     CDATA                                                #REQUIRED>
  <!ATTLIST PROPERTY ADDRESS  CDATA                                                #IMPLIED>
  <!ATTLIST PROPERTY TYPE     (string | long | int | double | void | bool | date | custom)  #IMPLIED>
  <!ATTLIST PROPERTY VALUE    CDATA                                                #IMPLIED>

<!ELEMENT BOOKMARKS (BOOKMARK*)>

<!ELEMENT BOOKMARK EMPTY>
  <!ATTLIST BOOKMARK ADDRESS     CDATA  #REQUIRED>
  <!ATTLIST BOOKMARK TYPE        CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK CATEGORY    CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK DESCRIPTION CDATA  #IMPLIED>

<!ELEMENT PROGRAM_TREES (TREE*)>

<!ELEMENT TREE ((FOLDER | FRAGMENT)*)>
  <!ATTLIST TREE NAME CDATA #REQUIRED>

<!ELEMENT FOLDER ((FOLDER | FRAGMENT)*)>
  <!ATTLIST FOLDER NAME CDATA #REQUIRED>

<!ELEMENT FRAGMENT (ADDRESS_RANGE)*>
  <!ATTLIST FRAGMENT NAME CDATA #REQUIRED>

<!ELEMENT ADDRESS_RANGE EMPTY>
  <!ATTLIST ADDRESS_RANGE START  CDATA  #REQUIRED>
  <!ATTLIST ADDRESS_RANGE END    CDATA  #REQUIRED>

<!ELEMENT PROGRAM_ENTRY_POINTS (PROGRAM_ENTRY_POINT*)>

<!ELEMENT PROGRAM_ENTRY_POINT EMPTY>
  <!ATTLIST PROGRAM_ENTRY_POINT  ADDRESS  CDATA  #REQUIRED>

<!ELEMENT RELOCATION_TABLE (RELOCATION*)>

<!ELEMENT RELOCATION EMPTY>
  <!ATTLIST RELOCATION ADDRESS  	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION STATUS    	( UNKNOWN | SKIPPED | UNSUPPORTED | FAILURE | PARTIAL | APPLIED | APPLIED_OTHER )	#IMPLIED>
  <!-- STATUS defaults to APPLIED if BYTES specified and TYPE is non-zero  -->
  <!-- STATUS defaults to APPLIED_OTHER if BYTES specified and TYPE is zero  -->
  <!-- STATUS defaults to UNKNOWN if BYTES are not specified  -->
  <!ATTLIST RELOCATION TYPE     	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION VALUE    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION BYTES    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION SYMBOL_NAME	CDATA	#IMPLIED>

<!ELEMENT SYMBOL_TABLE (SYMBOL*)>

<!ELEMENT SYMBOL EMPTY>
  <!ATTLIST SYMBOL ADDRESS   		CDATA            					 #REQUIRED>
  <!ATTLIST SYMBOL NAME      		CDATA             					 #REQUIRED>
  <!ATTLIST SYMBOL NAMESPACE 		CDATA             					 #IMPLIED>
  <!ATTLIST SYMBOL TYPE      		(global | local)  					 #IMPLIED>
  <!ATTLIST SYMBOL SOURCE_TYPE      (USER_DEFINED | IMPORTED | ANALYSIS) #IMPLIED>
  <!ATTLIST SYMBOL PRIMARY   		(y | n)           					 #IMPLIED>
  <!ATTLIST SYMBOL MANGLED   		CDATA             					 #IMPLIED>

<!ELEMENT FUNCTIONS (FUNCTION*)>

<!ELEMENT FUNCTION (RETURN_TYPE?, ADDRESS_RANGE*, REGULAR_CMT?, REPEATABLE_CMT?, TYPEINFO_CMT?, STACK_FRAME?, REGISTER_VAR*)>
  <!ATTLIST FUNCTION ENTRY_POINT       CDATA   #REQUIRED>
  <!ATTLIST FUNCTION NAME              CDATA   #IMPLIED>
  <!-- TODO: create xml attrs for each known attribute type -->
  <!ATTLIST FUNCTION LIBRARY_FUNCTION  (y | n) #IMPLIED>

<!ELEMENT RETURN_TYPE EMPTY>
  <!ATTLIST RETURN_TYPE DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST RETURN_TYPE DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST RETURN_TYPE SIZE                CDATA  #IMPLIED>

<!ELEMENT STACK_FRAME (STACK_VAR*)>
  <!ATTLIST STACK_FRAME LOCAL_VAR_SIZE         CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME PARAM_OFFSET           CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME REGISTER_SAVE_SIZE     CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME RETURN_ADDR_SIZE       CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME BYTES_PURGED           CDATA    #IMPLIED>

<!ELEMENT STACK_VAR (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST STACK_VAR STACK_PTR_OFFSET    CDATA  #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_VAR FRAME_PTR_OFFSET    CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR NAME                CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST STACK_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR SIZE                CDATA  #IMPLIED>

<!ELEMENT REGISTER_VAR (REGULAR_CMT?)>
  <!ATTLIST REGISTER_VAR NAME                CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR REGISTER            CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR DATATYPE            CDATA  #IMPLIED>
  <!ATTLIST REGISTER_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT MARKUP (MEMORY_REFERENCE      |
                  STACK_REFERENCE       |
                  EXT_LIBRARY_REFERENCE |
                  EQUATE_REFERENCE      |
                  MANUAL_OPERAND        |
                  MANUAL_INSTRUCTION)*>

<!-- An OPERAND_INDEX is omitted for a mnemonic reference    -->
<!-- The first operand is identified with OPERAND_INDEX=0 -->
<!ELEMENT MEMORY_REFERENCE EMPTY>
  <!ATTLIST MEMORY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE TO_ADDRESS     CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE BASE_ADDRESS   CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE PRIMARY        (y | n)  #IMPLIED>

<!ELEMENT STACK_REFERENCE EMPTY>
  <!ATTLIST STACK_REFERENCE ADDRESS          CDATA    #REQUIRED>
  <!ATTLIST STACK_REFERENCE OPERAND_INDEX    CDATA    #IMPLIED>
  <!ATTLIST STACK_REFERENCE USER_DEFINED     (y | n)  #IMPLIED>
  <!ATTLIST STACK_REFERENCE STACK_PTR_OFFSET CDATA    #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_REFERENCE FRAME_PTR_OFFSET CDATA    #IMPLIED>

<!ELEMENT EXT_LIBRARY_REFERENCE EMPTY>
  <!ATTLIST EXT_LIBRARY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_PROG_NAME  CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_LABEL      CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ORDINAL    CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ADDR       CDATA    #IMPLIED>

<!ELEMENT EQUATE_REFERENCE EMPTY>
  <!ATTLIST EQUATE_REFERENCE ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE OPERAND_INDEX  CDATA  #IMPLIED>
  <!ATTLIST EQUATE_REFERENCE NAME           CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE VALUE          CDATA  #IMPLIED>

<!ELEMENT MANUAL_OPERAND (#PCDATA)>
  <!ATTLIST MANUAL_OPERAND ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST MANUAL_OPERAND OPERAND_INDEX  CDATA  #REQUIRED>

<!ELEMENT MANUAL_INSTRUCTION (#PCDATA)>
  <!ATTLIST MANUAL_INSTRUCTION ADDRESS CDATA #REQUIRED>

<!ELEMENT EXT_LIBRARY_TABLE (EXT_LIBRARY*)>

<!ELEMENT EXT_LIBRARY EMPTY>
  <!ATTLIST EXT_LIBRARY NAME  CDATA  #REQUIRED>
  <!ATTLIST EXT_LIBRARY PATH  CDATA  #IMPLIED>

<!-- ************************************************************* -->
<!--                                                               -->
<!--                Data DTD                                       -->
<!--                                                               -->
<!-- ************************************************************* -->

<!ELEMENT DATATYPES (STRUCTURE | UNION | FUNCTION_DEF | ENUM | TYPE_DEF)*>

<!ELEMENT MEMBER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST MEMBER OFFSET              CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST MEMBER NAME                CDATA  #IMPLIED>
  <!ATTLIST MEMBER SIZE                CDATA  #IMPLIED>

<!ELEMENT STRUCTURE (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST STRUCTURE NAME             CDATA   #REQUIRED>
  <!ATTLIST STRUCTURE NAMESPACE        CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE SIZE             CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE VARIABLE_LENGTH  (y | n) #IMPLIED>

<!ELEMENT UNION (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST UNION NAME       CDATA  #REQUIRED>
  <!ATTLIST UNION NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST UNION SIZE       CDATA  #IMPLIED>

<!ELEMENT FUNCTION_DEF (REGULAR_CMT?, REPEATABLE_CMT?, RETURN_TYPE?, PARAMETER*)>
  <!ATTLIST FUNCTION_DEF NAME       CDATA  #REQUIRED>
  <!ATTLIST FUNCTION_DEF NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT PARAMETER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST PARAMETER ORDINAL             CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST PARAMETER NAME                CDATA  #IMPLIED>
  <!ATTLIST PARAMETER SIZE                CDATA  #IMPLIED>

<!ELEMENT TYPE_DEF (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST TYPE_DEF NAME                CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF NAMESPACE           CDATA #IMPLIED>
  <!ATTLIST TYPE_DEF DATATYPE            CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF DATATYPE_NAMESPACE  CDATA #IMPLIED>

<!ELEMENT ENUM (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, ENUM_ENTRY*)>
  <!ATTLIST ENUM NAME       CDATA  #REQUIRED>
  <!ATTLIST ENUM NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST ENUM SIZE       CDATA  #IMPLIED>

<!ELEMENT ENUM_ENTRY (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST ENUM_ENTRY NAME   	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY VALUE  	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY COMMENT  CDATA  #REQUIRED>

]>
<PROGRAM NAME="AARCH64-64-cpu0x0" EXE_PATH="/AARCH64-64-cpu0x0" EXE_FORMAT="Mac OS X Mach-O" IMAGE_BASE="00000000">
    <INFO_SOURCE USER="antoinebedos" TOOL="Ghidra 12.0" TIMESTAMP="Tue Mar 17 15:04:34 CET 2026" />
    <PROCESSOR NAME="AARCH64" LANGUAGE_PROVIDER="AARCH64:LE:64:AppleSilicon:default" ENDIAN="little" />
    <DATATYPES>
        <TYPE_DEF NAME="__darwin_blkcnt_t" NAMESPACE="/_types.h" DATATYPE="__int64_t" DATATYPE_NAMESPACE="/_types.h" />
        <TYPE_DEF NAME="__darwin_blksize_t" NAMESPACE="/_types.h" DATATYPE="__int32_t" DATATYPE_NAMESPACE="/_types.h" />
        <TYPE_DEF NAME="__darwin_dev_t" NAMESPACE="/_types.h" DATATYPE="__int32_t" DATATYPE_NAMESPACE="/_types.h" />
        <TYPE_DEF NAME="__darwin_gid_t" NAMESPACE="/_types.h" DATATYPE="__uint32_t" DATATYPE_NAMESPACE="/_types.h" />
        <TYPE_DEF NAME="__darwin_ino64_t" NAMESPACE="/_types.h" DATATYPE="__uint64_t" DATATYPE_NAMESPACE="/_types.h" />
        <TYPE_DEF NAME="__darwin_mode_t" NAMESPACE="/_types.h" DATATYPE="__uint16_t" DATATYPE_NAMESPACE="/_types.h" />
        <TYPE_DEF NAME="__darwin_off_t" NAMESPACE="/_types.h" DATATYPE="__int64_t" DATATYPE_NAMESPACE="/_types.h" />
        <TYPE_DEF NAME="__darwin_pthread_attr_t" NAMESPACE="/_types.h" DATATYPE="_opaque_pthread_attr_t" DATATYPE_NAMESPACE="/_types.h" />
        <STRUCTURE NAME="__darwin_pthread_handler_rec" NAMESPACE="/_types.h" SIZE="0x18">
            <MEMBER OFFSET="0x0" DATATYPE="_func_1 *" DATATYPE_NAMESPACE="/_types.h/functions" NAME="__routine" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="__arg" SIZE="0x8" />
            <MEMBER OFFSET="0x10" DATATYPE="__darwin_pthread_handler_rec *" DATATYPE_NAMESPACE="/_types.h" NAME="__next" SIZE="0x8" />
        </STRUCTURE>
        <TYPE_DEF NAME="__darwin_pthread_key_t" NAMESPACE="/_types.h" DATATYPE="ulong" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="__darwin_pthread_mutex_t" NAMESPACE="/_types.h" DATATYPE="_opaque_pthread_mutex_t" DATATYPE_NAMESPACE="/_types.h" />
        <TYPE_DEF NAME="__darwin_pthread_mutexattr_t" NAMESPACE="/_types.h" DATATYPE="_opaque_pthread_mutexattr_t" DATATYPE_NAMESPACE="/_types.h" />
        <TYPE_DEF NAME="__darwin_pthread_t" NAMESPACE="/_types.h" DATATYPE="_opaque_pthread_t *" DATATYPE_NAMESPACE="/_types.h" />
        <TYPE_DEF NAME="__darwin_size_t" NAMESPACE="/_types.h" DATATYPE="ulong" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="__darwin_time_t" NAMESPACE="/_types.h" DATATYPE="long" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="__darwin_uid_t" NAMESPACE="/_types.h" DATATYPE="__uint32_t" DATATYPE_NAMESPACE="/_types.h" />
        <TYPE_DEF NAME="__int32_t" NAMESPACE="/_types.h" DATATYPE="int" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="__int64_t" NAMESPACE="/_types.h" DATATYPE="longlong" DATATYPE_NAMESPACE="/" />
        <STRUCTURE NAME="__sbuf" NAMESPACE="/stdio.h" SIZE="0x10">
            <MEMBER OFFSET="0x0" DATATYPE="uchar *" DATATYPE_NAMESPACE="/" NAME="_base" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="_size" SIZE="0x4" />
        </STRUCTURE>
        <STRUCTURE NAME="__sFILE" NAMESPACE="/stdio.h" SIZE="0x98">
            <MEMBER OFFSET="0x0" DATATYPE="uchar *" DATATYPE_NAMESPACE="/" NAME="_p" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="_r" SIZE="0x4" />
            <MEMBER OFFSET="0xc" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="_w" SIZE="0x4" />
            <MEMBER OFFSET="0x10" DATATYPE="short" DATATYPE_NAMESPACE="/" NAME="_flags" SIZE="0x2" />
            <MEMBER OFFSET="0x12" DATATYPE="short" DATATYPE_NAMESPACE="/" NAME="_file" SIZE="0x2" />
            <MEMBER OFFSET="0x18" DATATYPE="__sbuf" DATATYPE_NAMESPACE="/stdio.h" NAME="_bf" SIZE="0x10" />
            <MEMBER OFFSET="0x28" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="_lbfsize" SIZE="0x4" />
            <MEMBER OFFSET="0x30" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="_cookie" SIZE="0x8" />
            <MEMBER OFFSET="0x38" DATATYPE="_func_2 *" DATATYPE_NAMESPACE="/stdio.h/functions" NAME="_close" SIZE="0x8" />
            <MEMBER OFFSET="0x40" DATATYPE="_func_3 *" DATATYPE_NAMESPACE="/stdio.h/functions" NAME="_read" SIZE="0x8" />
            <MEMBER OFFSET="0x48" DATATYPE="_func_4 *" DATATYPE_NAMESPACE="/stdio.h/functions" NAME="_seek" SIZE="0x8" />
            <MEMBER OFFSET="0x50" DATATYPE="_func_5 *" DATATYPE_NAMESPACE="/stdio.h/functions" NAME="_write" SIZE="0x8" />
            <MEMBER OFFSET="0x58" DATATYPE="__sbuf" DATATYPE_NAMESPACE="/stdio.h" NAME="_ub" SIZE="0x10" />
            <MEMBER OFFSET="0x68" DATATYPE="__sFILEX *" DATATYPE_NAMESPACE="/stdio.h" NAME="_extra" SIZE="0x8" />
            <MEMBER OFFSET="0x70" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="_ur" SIZE="0x4" />
            <MEMBER OFFSET="0x74" DATATYPE="uchar[3]" DATATYPE_NAMESPACE="/" NAME="_ubuf" SIZE="0x3" />
            <MEMBER OFFSET="0x77" DATATYPE="uchar[1]" DATATYPE_NAMESPACE="/" NAME="_nbuf" SIZE="0x1" />
            <MEMBER OFFSET="0x78" DATATYPE="__sbuf" DATATYPE_NAMESPACE="/stdio.h" NAME="_lb" SIZE="0x10" />
            <MEMBER OFFSET="0x88" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="_blksize" SIZE="0x4" />
            <MEMBER OFFSET="0x90" DATATYPE="fpos_t" DATATYPE_NAMESPACE="/stdio.h" NAME="_offset" SIZE="0x8" />
        </STRUCTURE>
        <STRUCTURE NAME="__sFILEX" NAMESPACE="/stdio.h" SIZE="0x0" />
        <STRUCTURE NAME="__shared_weak_count" NAMESPACE="/Demangler/std" SIZE="0x0">
            <REGULAR_CMT>PlaceHolder Structure</REGULAR_CMT>
        </STRUCTURE>
        <STRUCTURE NAME="__state" NAMESPACE="/Demangler/std" SIZE="0x0">
            <REGULAR_CMT>PlaceHolder Structure</REGULAR_CMT>
        </STRUCTURE>
        <STRUCTURE NAME="__thread_struct" NAMESPACE="/Demangler/std" SIZE="0x0">
            <REGULAR_CMT>PlaceHolder Structure</REGULAR_CMT>
        </STRUCTURE>
        <TYPE_DEF NAME="__uint16_t" NAMESPACE="/_types.h" DATATYPE="ushort" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="__uint32_t" NAMESPACE="/_types.h" DATATYPE="uint" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="__uint64_t" NAMESPACE="/_types.h" DATATYPE="ulonglong" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="__uint8_t" NAMESPACE="/_types.h" DATATYPE="uchar" DATATYPE_NAMESPACE="/" />
        <FUNCTION_DEF NAME="_func_1" NAMESPACE="/_types.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="void" DATATYPE_NAMESPACE="/" SIZE="0x0" />
            <PARAMETER ORDINAL="0x0" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x8" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="_func_11423" NAMESPACE="/unwind.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="void" DATATYPE_NAMESPACE="/" SIZE="0x0" />
            <PARAMETER ORDINAL="0x0" DATATYPE="_Unwind_Reason_Code" DATATYPE_NAMESPACE="/unwind.h" NAME="reason" SIZE="0x4" />
            <PARAMETER ORDINAL="0x1" DATATYPE="_Unwind_Exception *" DATATYPE_NAMESPACE="/unwind.h" NAME="exc" SIZE="0x8" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="_func_2" NAMESPACE="/stdio.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="int" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x8" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="_func_3" NAMESPACE="/stdio.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="int" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x8" />
            <PARAMETER ORDINAL="0x1" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x8" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="_func_4" NAMESPACE="/stdio.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="fpos_t" DATATYPE_NAMESPACE="/stdio.h" SIZE="0x8" />
            <PARAMETER ORDINAL="0x0" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x8" />
            <PARAMETER ORDINAL="0x1" DATATYPE="fpos_t" DATATYPE_NAMESPACE="/stdio.h" NAME="" SIZE="0x8" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <FUNCTION_DEF NAME="_func_5" NAMESPACE="/stdio.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="int" DATATYPE_NAMESPACE="/" SIZE="0x4" />
            <PARAMETER ORDINAL="0x0" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x8" />
            <PARAMETER ORDINAL="0x1" DATATYPE="char *" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x8" />
            <PARAMETER ORDINAL="0x2" DATATYPE="int" DATATYPE_NAMESPACE="/" NAME="" SIZE="0x4" />
        </FUNCTION_DEF>
        <STRUCTURE NAME="_opaque_pthread_attr_t" NAMESPACE="/_types.h" SIZE="0x40">
            <MEMBER OFFSET="0x0" DATATYPE="long" DATATYPE_NAMESPACE="/" NAME="__sig" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="char[56]" DATATYPE_NAMESPACE="/" NAME="__opaque" SIZE="0x38" />
        </STRUCTURE>
        <STRUCTURE NAME="_opaque_pthread_mutex_t" NAMESPACE="/_types.h" SIZE="0x40">
            <MEMBER OFFSET="0x0" DATATYPE="long" DATATYPE_NAMESPACE="/" NAME="__sig" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="char[56]" DATATYPE_NAMESPACE="/" NAME="__opaque" SIZE="0x38" />
        </STRUCTURE>
        <STRUCTURE NAME="_opaque_pthread_mutexattr_t" NAMESPACE="/_types.h" SIZE="0x10">
            <MEMBER OFFSET="0x0" DATATYPE="long" DATATYPE_NAMESPACE="/" NAME="__sig" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="char[8]" DATATYPE_NAMESPACE="/" NAME="__opaque" SIZE="0x8" />
        </STRUCTURE>
        <STRUCTURE NAME="_opaque_pthread_t" NAMESPACE="/_types.h" SIZE="0x4a0">
            <MEMBER OFFSET="0x0" DATATYPE="long" DATATYPE_NAMESPACE="/" NAME="__sig" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="__darwin_pthread_handler_rec *" DATATYPE_NAMESPACE="/_types.h" NAME="__cleanup_stack" SIZE="0x8" />
            <MEMBER OFFSET="0x10" DATATYPE="char[1168]" DATATYPE_NAMESPACE="/" NAME="__opaque" SIZE="0x490" />
        </STRUCTURE>
        <STRUCTURE NAME="_Unwind_Exception" NAMESPACE="/unwind.h" SIZE="0x30">
            <MEMBER OFFSET="0x0" DATATYPE="uint64_t" DATATYPE_NAMESPACE="/_uint64_t.h" NAME="exception_class" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="_func_11423 *" DATATYPE_NAMESPACE="/unwind.h/functions" NAME="exception_cleanup" SIZE="0x8" />
            <MEMBER OFFSET="0x10" DATATYPE="uintptr_t" DATATYPE_NAMESPACE="/_uintptr_t.h" NAME="private_1" SIZE="0x8" />
            <MEMBER OFFSET="0x18" DATATYPE="uintptr_t" DATATYPE_NAMESPACE="/_uintptr_t.h" NAME="private_2" SIZE="0x8" />
            <MEMBER OFFSET="0x20" DATATYPE="uint32_t[3]" DATATYPE_NAMESPACE="/_uint32_t.h" NAME="reserved" SIZE="0xc" />
        </STRUCTURE>
        <TYPE_DEF NAME="_Unwind_Reason_Code" NAMESPACE="/unwind.h" DATATYPE="enum_4370" DATATYPE_NAMESPACE="/unwind.h" />
        <STRUCTURE NAME="allocator" NAMESPACE="/Demangler/std" SIZE="0x0">
            <REGULAR_CMT>PlaceHolder Structure</REGULAR_CMT>
        </STRUCTURE>
        <STRUCTURE NAME="bad_alloc" NAMESPACE="/Demangler/std" SIZE="0x0">
            <REGULAR_CMT>PlaceHolder Structure</REGULAR_CMT>
        </STRUCTURE>
        <STRUCTURE NAME="bad_array_new_length" NAMESPACE="/Demangler/std" SIZE="0x0">
            <REGULAR_CMT>PlaceHolder Structure</REGULAR_CMT>
        </STRUCTURE>
        <STRUCTURE NAME="bad_cast" NAMESPACE="/Demangler/std" SIZE="0x0">
            <REGULAR_CMT>PlaceHolder Structure</REGULAR_CMT>
        </STRUCTURE>
        <ENUM NAME="bind_opcode" NAMESPACE="/MachO" SIZE="0x1">
            <ENUM_ENTRY NAME="BIND_OPCODE_DONE" VALUE="0x0" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_SET_DYLIB_ORDINAL_IMM" VALUE="0x10" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_SET_DYLIB_ORDINAL_ULEB" VALUE="0x20" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_SET_DYLIB_SPECIAL_IMM" VALUE="0x30" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_SET_SYMBOL_TRAILING_FLAGS_IMM" VALUE="0x40" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_SET_TYPE_IMM" VALUE="0x50" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_SET_ADDEND_SLEB" VALUE="0x60" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB" VALUE="0x70" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_ADD_ADDR_ULEB" VALUE="0x80" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_DO_BIND" VALUE="0x90" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_DO_BIND_ADD_ADDR_ULEB" VALUE="0xa0" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_DO_BIND_ADD_ADDR_IMM_SCALED" VALUE="0xb0" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_DO_BIND_ULEB_TIMES_SKIPPING_ULEB" VALUE="0xc0" COMMENT="" />
            <ENUM_ENTRY NAME="BIND_OPCODE_THREADED" VALUE="0xd0" COMMENT="" />
        </ENUM>
        <TYPE_DEF NAME="blkcnt_t" NAMESPACE="/_blkcnt_t.h" DATATYPE="__darwin_blkcnt_t" DATATYPE_NAMESPACE="/_types.h" />
        <TYPE_DEF NAME="blksize_t" NAMESPACE="/_blksize_t.h" DATATYPE="__darwin_blksize_t" DATATYPE_NAMESPACE="/_types.h" />
        <STRUCTURE NAME="build_tool_version" NAMESPACE="/MachO" SIZE="0x8">
            <MEMBER OFFSET="0x0" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="tool" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="version" SIZE="0x4" />
        </STRUCTURE>
        <STRUCTURE NAME="build_version_command" NAMESPACE="/MachO" SIZE="0x20">
            <MEMBER OFFSET="0x0" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="cmd" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="cmdsize" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="platform" SIZE="0x4" />
            <MEMBER OFFSET="0xc" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="minos" SIZE="0x4" />
            <MEMBER OFFSET="0x10" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sdk" SIZE="0x4" />
            <MEMBER OFFSET="0x14" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="ntools" SIZE="0x4" />
            <MEMBER OFFSET="0x18" DATATYPE="build_tool_version[1]" DATATYPE_NAMESPACE="/MachO" NAME="build_tool_version[]" SIZE="0x8" />
        </STRUCTURE>
        <TYPE_DEF NAME="Cache" NAMESPACE="/" DATATYPE="qword" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="CC_LONG" NAMESPACE="/CommonDigest.h" DATATYPE="uint32_t" DATATYPE_NAMESPACE="/_uint32_t.h" />
        <STRUCTURE NAME="cfstringStruct" NAMESPACE="/" SIZE="0x20">
            <MEMBER OFFSET="0x0" DATATYPE="qword" DATATYPE_NAMESPACE="/" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="qword" DATATYPE_NAMESPACE="/" SIZE="0x8" />
            <MEMBER OFFSET="0x10" DATATYPE="pointer" DATATYPE_NAMESPACE="/" SIZE="0x8" />
            <MEMBER OFFSET="0x18" DATATYPE="long" DATATYPE_NAMESPACE="/" SIZE="0x8" />
        </STRUCTURE>
        <STRUCTURE NAME="class_rw_t" NAMESPACE="/_objc2_" SIZE="0x48">
            <MEMBER OFFSET="0x0" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="flags" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="instanceStart" SIZE="0x8" />
            <MEMBER OFFSET="0x10" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="instanceSize" SIZE="0x8" />